# Generated by Django 5.1.5 on 2025-02-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_players', models.IntegerField()),
                ('games_per_match', models.IntegerField(default=10)),
                ('total_execution_time', models.FloatField(null=True)),
                ('results', models.JSONField(null=True)),
            ],
        ),
    ]
