# Generated by Django 5.1.6 on 2025-03-23 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0002_uploadedfile_delete_tournamentexecution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
